// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACEa7IFNe7bGIdMTOsWMThNv38gzZGFik',
    appId: '1:519869384129:web:f5d1c8b54d150237029b40',
    messagingSenderId: '519869384129',
    projectId: 'insta-auto-ai',
    authDomain: 'insta-auto-ai.firebaseapp.com',
    storageBucket: 'insta-auto-ai.firebasestorage.app',
    measurementId: 'G-VT8XYKHYJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZdIsTFLOVg4WdnddHL9vHasttjYRV4Uo',
    appId: '1:519869384129:android:262300ed024e805f029b40',
    messagingSenderId: '519869384129',
    projectId: 'insta-auto-ai',
    storageBucket: 'insta-auto-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-4voEM9_IjhPfzDnl5lo8owWNW_btH2c',
    appId: '1:519869384129:ios:e587ed7b50e1318a029b40',
    messagingSenderId: '519869384129',
    projectId: 'insta-auto-ai',
    storageBucket: 'insta-auto-ai.firebasestorage.app',
    iosBundleId: 'com.example.instaautoai.instaAutoAi',
  );
}
